# Site settings
title: Matthew Bull
email: bull.matthew@gmail.com
description: "Matthew Bull is a web developer with 10 years' experience of PHP development, as well as recent experience of UX development and design."
baseurl: ""
url: "https://gnozu.github.io"

# Build settings
markdown: kramdown
permalink: pretty
